# route your build to the container-based infrastructure for a faster build
sudo: false

# from http://jekyllrb.com/docs/continuous-integration/
language: ruby
rvm:
- 2.2.5

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
# install: gem install jekyll html-proofer
install:
  - bundle install
  - gem install html-proofer
script: jekyll build && htmlproofer ./_site --disable-external --allow-hash-href

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master       # test the master branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
